name: beanRTP
version: ${project.version}
main: com.github.beanbeanjuice.beanrtp.beanRTP
api-version: 1.16
load: STARTUP
authors: [ beanbeanjuice ]
description: A random teleport plugin for spigot/paper.
website: youtube.com/beanbeanjuice

commands:
  testcommand:
    description: Test