package com.beanbeanjuice.beanrtp.utility.config;

public enum ConfigDataKey {
    PREFIX,
    MINIMUM_DISTANCE_FROM_BORDER_CENTER,
    ALLOWED_WORLDS,
    FALLBACK_WORLD,
    COOLDOWN_TIME,
    COUNTDOWN_TIME,

    NO_PERMISSION_MESSAGE,
    STARTING_TELEPORTATION_MESSAGE,
    SUCCESSFUL_TELEPORTATION_MESSAGE,
    UNSUCCESSFUL_TELEPORTATION_MESSAGE,
    OTHER_SUCCESSFUL_TELEPORTATION_MESSAGE,
    OTHER_UNSUCCESSFUL_TELEPORTATION_MESSAGE,
    MOVED_DURING_TELEPORT_MESSAGE,
    COOLDOWN_MESSAGE,
    SUCCESSFUL_RELOAD_MESSAGE,
    UNKNOWN_COMMAND_MESSAGE,
    NOT_ALLOWED_WORLD_MESSAGE,
    NOT_ALLOWED_WORLD_OTHERS_MESSAGE,
    ALREADY_TELEPORTING_MESSAGE,
    HELP_MESSAGE
}
